### ISSUE TITLE
Problem with qoutes in field

### ISSUE THREAD

**Issue by IDDemon** [antonycourtney/tad#110]
When a csv uses semicolon as a separator and a field contains text with quotes in it, TAD refuses to open the file with parsing error. Screenshot of error and a test file are attached. The test file is constructed from a larger file which is made by an unknown software but Microsoft Excel and even LibreOffice has no promlems with it.

<img width="430" alt="error" src="https://user-images.githubusercontent.com/28053355/28720583-e72bfdb2-73ad-11e7-8d70-0a3c7b523e91.png">
[test.csv.zip](https://github.com/antonycourtney/tad/files/1183241/test.csv.zip)

**Comment by antonycourtney** [comment]
Thanks for the detailed bug report and including a minimal file to reproduce the error. Will take a look.

**Comment by antonycourtney** [comment]
After a lengthy hiatus, finally have a chance to look at some old Tad bugs...

Digging into this one a bit, it looks to me like the CSV in question is actually malformed.
The original line in the test file is:
```
ANTRYKOT  WOLOWY 200 g;0.200;KG;Saving;x;"TADEX" TADEUSZ - SK10376_BLAKSZ;Fresh food
```
The problem is that CSV requires individual fields to be either entirely quoted (with literal quote characters escaped with two adjacent occurrences) or entirely unquoted.
If we replace the above with:
```
ANTRYKOT  WOLOWY 200 g;0.200;KG;Saving;x;"""TADEX"" TADEUSZ - SK10376_BLAKSZ";Fresh food
```
Note that triple quote marks at the start -- the first quote is matched by the quote character at the end of the field.  The following doubled quote characters escape the literal quotes around `"TADEX"`. This version of the file parses and renders correctly in Tad.

For European format CSV files, the parsing here is done by the [fast-csv](https://github.com/C2FO/fast-csv) library.  But my impression is that this isn't really a bug in that library.

Thanks again for reporting and providing a detailed test case.
Sincere apologies that this languished for a year and a half.
I hope this explanation is helpful.
