### ISSUE TITLE
Can't Expand Pivot on a Blank Cell

### ISSUE THREAD

**Issue by Ga68** [antonycourtney/tad#123]
When I pivot on a given column, there's values V1, V2, V3, etc. and in this case, there are some rows with no value (NULL, blank, etc.). They all get grouped together, which seems right, but when I click the + sign next to it to expand, they won't expand. All the row-groups with a value in the pivoted column expand as expected.

**Comment by antonycourtney** [comment]
I investigated this because it bit me yesterday.  It turns out to come down to sloppy / inconsistent handling of null values in string columns.  Some notes in case I get some cycles to eventually fix this:
First:  Our fast CSV import code seems to be importing empty strings from CSV files as `null` instead of as empty strings. It's actually not clear whether that's the right behavior. But since we want Tad to ultimately be usable for any kind of database table viewing (not just CSV files), it seems worth handling NULL values correctly.
Second: Our encoding of pivot tree paths in aggtree.js uses a `null` value in the synthetic `_path`N columns as a path terminator.  This processing happens in [onGridClick() in GridPane](https://github.com/antonycourtney/tad/blob/master/src/components/GridPane.js#L166).
We should probably just encode the length explicitly in `aggtree.js` to avoid this overloaded interpretation of NULL values for strings.
